// <auto-generated />
namespace PastelECia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class pastel03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pastel03));
        
        string IMigrationMetadata.Id
        {
            get { return "202211232010490_pastel03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
